# Generated by Django 4.1 on 2022-08-05 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=5000)),
                ('genre', models.CharField(choices=[('p', 'politics'), ('s', 'sports'), ('g', 'gaming'), ('h', 'health'), ('m', 'music')], max_length=10)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
