# Generated by Django 4.1 on 2022-08-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_creator_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='genre',
        ),
    ]
